#define OFFCOUNT 127 //Official Count
//Unofficial additions
#define PT_FPLT OFFCOUNT + 1
#define PT_SOAP OFFCOUNT + 2
#define PT_REMT OFFCOUNT + 3
#define PT_RREC OFFCOUNT + 4
#define PT_PROT OFFCOUNT + 5
#define PT_WAVE OFFCOUNT + 6
#define PT_EWAVE OFFCOUNT + 7
#define PT_INTF OFFCOUNT + 8
#define PT_AEMT OFFCOUNT + 9
#define PT_AREC OFFCOUNT + 10
#define PT_AWAVE OFFCOUNT + 11
#define PT_BEMT OFFCOUNT + 12
#define PT_BREC OFFCOUNT + 13
#define PT_BWAVE OFFCOUNT + 14
#define PT_CEMT OFFCOUNT + 15
#define PT_CREC OFFCOUNT + 16
#define PT_CWAVE OFFCOUNT + 17
#define PT_WEMT	OFFCOUNT + 18
#define PT_WREC	OFFCOUNT + 19
#define PT_PGLW OFFCOUNT + 20
#define PT_IEMT OFFCOUNT + 21
#define PT_IREC OFFCOUNT + 22
#define PT_IWAVE OFFCOUNT + 23
//Unofficial Count
#define PT_NUM  OFFCOUNT + 24
