//			if low pressure		if high pressure	if low temperature	if high temperature
// Name		plv		plt	 		phv		pht			tlv		    tlt	 		thv		    tht
/* FPLT */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,		    773.15f,    PT_FIRE},
/* SOAP */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			ITH,	    NT},
/* REMT */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			1273.15f,   PT_LAVA},
/* RREC */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			1273.15f,   PT_LAVA},
/* CHAN */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			ITH,	    NT},
/* PROT */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			ITH,	    NT},
/* WAVE */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			ITH,	    NT},
/* WAVE */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			ITH,	    NT},
/* INTF */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			ITH,	    NT},
/* WEMT */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			1273.15f,   PT_LAVA},
/* WREC */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			1273.15f,   PT_LAVA},
/* PGLW */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			ITH,	    NT},
/* IEMT */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			1273.15f,   PT_LAVA},
/* IREC */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			1273.15f,   PT_LAVA},
/* IWAV */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			ITH,	    NT},
/* HGEN */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			1273.15f,   PT_LAVA},
/* HWAV */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			ITH,	    NT},
/* CHLN */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			ITH,	    NT},
/* TUNN */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			ITH,	    NT},
/* VTNN */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			ITH,	    NT},
/* EXPL */ {-.5f,	PT_PLSM,	0.5f,	PT_PLSM,	295.14f,    PT_PLSM,	295.16f,	PT_PLSM},
/* PRSN */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			ITH,	    NT},
/* CSTR */ {IPL,	NT,			IPH,	NT,			ITL,	    NT,			ITH,	    NT},
// Name		plv		plt	 		phv		pht			tlv		    tlt	 		thv		    tht
//			if low pressure		if high pressure	if low temperature	if high temperature
